services:
  accounts:
    image: "sakshi2505/accounts:s2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  loans:
    image: "sakshi2505/loans:s2"
    container_name: loans-ms
    ports:
       - "8091:8091"
    deploy:
      resources:
         limits:
          memory: 700m
    networks:
      - bank
  cards:
    image: "sakshi2505/cards:s2"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
networks:
  bank:
    driver: "bridge"