server:
  port: 8091
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: "3.O"

loans:
  message: "Welcome to Banking loans related local API's"
  contactDetails:
    name: "Sakshi Agrawal- Developer"
    email: "sakshiagrawal259@gmail.com"
  onCallSupport:
    -999-999-999