spring:
  config:
    activate:
      on-profile: "prod"


build:
  version: "1.O"

accounts:
  message: "Welcome to Banking accounts related Production API's"
  contactDetails:
    name: "Pinky Agrawal- Developer"
    email: "pinkyagrawal259@gmail.com"
  onCallSupport:
    -999-999-789